# Generated by Django 5.0 on 2024-01-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
