# Generated by Django 5.0 on 2024-01-28 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_cid'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('date', models.DateTimeField()),
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(max_length=50)),
                ('sphone', models.CharField(max_length=15)),
                ('smail', models.CharField(max_length=100)),
                ('saddress', models.CharField(max_length=100)),
                ('sbalance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
